# stage de build
FROM golang:1.20-bullseye AS build

RUN apt-get update -y

WORKDIR /go/src
COPY go.mod go.sum ./
RUN go mod download all && go mod verify
COPY . .

RUN CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o api /go/src/cmd/api/main.go

# final image
FROM gcr.io/distroless/base-debian11

WORKDIR /go/src
COPY --from=build /go/src/api ./

EXPOSE ${PORT:-3333}

CMD [ "/go/src/api" ]
