FROM golang:1.20-bullseye AS build

WORKDIR /go/src

COPY go.mod go.sum ./

RUN go mod download all && go mod verify
RUN go install github.com/cosmtrek/air@latest

COPY . .

EXPOSE ${PORT:-3333}

CMD ["air"]
