apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  namespace: finances
  labels:
    app: api
data:
  PORT: "3333"
  LOCAL_PORT: "3301"
  APP_ENV: "staging"

  JWT_SECRET_KEY: "secret123"
  JWT_EXPIRES_IN_SECONDS: "86400"
  JWT_PUBLIC_TOKEN: "abc123"

  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""

  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_NAME: "development"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  DB_TIMEZONE: "UTC"
  DB_ENABLED_SSL: "false"
  DB_LOGGING: "true"

  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  REDIS_DATABASE: "0"

  SLACK_TOKEN: ""
  SLACK_CHANNEL: "channel name"
  SLACK_MEMBER_ID: ""
  SLACK_USERNAME: "golang api"